# Generated by Django 4.1 on 2022-09-08 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_listing_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='choose_categories', to='auctions.category'),
        ),
    ]
