# Generated by Django 4.1 on 2022-09-11 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_alter_listing_bid_bidding'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bidding',
            old_name='bidding',
            new_name='bid',
        ),
    ]
