# Generated by Django 4.1 on 2022-09-11 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_alter_listing_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidding',
            name='bid',
            field=models.DecimalField(decimal_places=2, default=False, max_digits=6),
        ),
    ]
